name: Publish And Deploy Demo
on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    # 下载源码
    - name: Checkout
      uses: actions/checkout@master

    # 打包构建
    - name: Build
      uses: actions/setup-node@master
#     - run: npm install
#     - run: npm run build
    - run: zip -q -r release.zip
    - run: scp release.zip ${{ secrets.USERNAME }}@${{ secrets.HOST }}/root/node-test
    
    # 部署到服务器
    - name: Deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: |
          cd /root/node-test
          npm run stop
          rm -rf *
          unzip release.zip
          npm install --production
          npm run tsc
          npm run start
